spring:
  application:
    name: auth-service

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  cloud:
    openfeign:
      client:
        config:
            user-service:
                url: http://user-service:8081
                connect-timeout: 5000
                read-timeout: 5000

server:
  port: 8082

