spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

  mail:
    host: smtp.gmail.com
    port: 587
    username: danniyeres@gmail.com
    password: "mdlx tmux vxpb wdzp"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true