spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/user/**

        - id: auth-service
          uri: http://auth-service:8082
          predicates:
              - Path=/auth/**

        - id: account-service
          uri: http://account-service:8083
          predicates:
              - Path=/account/**
          filters:
            - AuthFilter

        - id: transaction-service
          uri: http://transaction-service:8084
          predicates:
              - Path=/transaction/**
          filters:
            - AuthFilter

server:
  port: 8080
