spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://account_db:5432/bank_account
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      client:
        config:
          user-service:
            url: http://user-service:8081
            connect-timeout: 5000
            read-timeout: 5000
server:
  port: 8083
